[project]
name = "unified-arp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.9.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.2",
    "solara>=1.54.0",
]
